name: Foo
on:
  pull_request:
  pull_request_target:
    types: [labeled]
jobs:
  foo:
    if: >-
      (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name,'safe-to-test')) ||
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
    runs-on: ubuntu-latest
    steps:
      - name: Decide which ref to checkout
        id: decide-ref
        run: |
          if [[ "${{github.event_name}}" == "pull_request" ]]; then
            echo "::set-output name=ref::${{github.ref}}"
          else
            echo "::set-output name=ref::refs/pull/${{ github.event.pull_request.number }}/merge"
          fi

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{steps.decide-refs.outputs.ref}}
          
      - name: debug info
        run: |
          echo event name: ${{ github.event_name }}
          echo repo full name: ${{ github.event.pull_request.head.repo.full_name }}
          echo repository: ${{ github.repository }}
          echo fork: ${{ github.event.pull_request.head.repo.fork }}
          echo repo id: ${{ github.event.pull_request.head.repo.id }}
          echo base repo id: ${{ github.event.pull_request.base.repo.id }}
          echo pr base sha: ${{ github.event.pull_request.base.sha }}
          echo pr head sha: ${{ github.event.pull_request.head.sha }}
          echo pr merge sha: ${{ github.event.pull_request.merge.sha }}
          echo git log commit head sha: $(git log -1 --format="%H")
          printenv

      - name: ls
        run: ls
      - name: foo
        run: echo "do stuff involving [${{ secrets.Foo }}]"